# -*- coding: utf-8 -*-
"""Comment_Toxicity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eaevWiQw83x1DHPGAMNXrQDL2OAmHX6-
"""

!pip install torch torchtext pandas numpy scikit-learn matplotlib seaborn --quiet

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np

df = pd.read_csv("train.csv")
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("\nFirst 3 rows:")
df.head(3)

import re, string, pickle
from collections import Counter
from torch.utils.data import Dataset, DataLoader
import torch

# ── constants ──────────────────────────────────────────
MAX_VOCAB  = 20000
MAX_LEN    = 200
BATCH_SIZE = 64
LABELS     = ['toxic','severe_toxic','obscene','threat','insult','identity_hate']

# ── text cleaner ───────────────────────────────────────
def clean(text):
    text = str(text).lower()
    text = text.translate(str.maketrans('','', string.punctuation))
    return text.split()

# ── build vocabulary from training data ───────────────
print("Building vocabulary...")
counter = Counter()
for txt in df['comment_text']:
    counter.update(clean(txt))

# Keep top MAX_VOCAB words; index 0=pad, 1=unknown
vocab = ['', ''] + [w for w, _ in counter.most_common(MAX_VOCAB - 2)]
word2idx = {w: i for i, w in enumerate(vocab)}
print(f"Vocabulary size: {len(vocab):,}")

# ── save vocab for later use in the Streamlit app ─────
with open("vectorizer_vocab.pkl", "wb") as f:
    pickle.dump(vocab, f)
print("Vocab saved → vectorizer_vocab.pkl")

# ── tokenize one text → padded list of ints ───────────
def tokenize(text):
    tokens = clean(text)[:MAX_LEN]
    ids    = [word2idx.get(t, 1) for t in tokens]
    ids   += [0] * (MAX_LEN - len(ids))   # pad to MAX_LEN
    return ids

from sklearn.model_selection import train_test_split

class ToxicDataset(Dataset):
    def __init__(self, texts, labels):
        self.X = [tokenize(t) for t in texts]
        self.y = labels

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return (
            torch.tensor(self.X[idx], dtype=torch.long),
            torch.tensor(self.y[idx], dtype=torch.float32),
        )

# split 90% train / 10% validation
train_df, val_df = train_test_split(df, test_size=0.1, random_state=42)

train_ds = ToxicDataset(train_df['comment_text'].tolist(),
                         train_df[LABELS].values)
val_ds   = ToxicDataset(val_df['comment_text'].tolist(),
                         val_df[LABELS].values)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE)

print(f"Train batches : {len(train_loader)}")
print(f"Val   batches : {len(val_loader)}")

# ── CELL 5+6 COMBINED : Define model + Train ──────────────────────────────────
import torch
import torch.nn as nn

# ── constants ──────────────────────────────────────────────────────────────────
VOCAB_SIZE  = len(vocab)      # set in Cell 3 (should be ~20000)
EMBED_DIM   = 128
LSTM_UNITS  = 64
DENSE_UNITS = 64
NUM_LABELS  = 6
EPOCHS      = 3               # increase to 5-10 for better accuracy

# ── model definition ───────────────────────────────────────────────────────────
class ToxicityModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.embedding = nn.Embedding(VOCAB_SIZE, EMBED_DIM, padding_idx=0)
        self.bilstm    = nn.LSTM(EMBED_DIM, LSTM_UNITS,
                                  batch_first=True, bidirectional=True)
        self.dense1    = nn.Linear(LSTM_UNITS * 2, DENSE_UNITS)
        self.relu      = nn.ReLU()
        self.dropout   = nn.Dropout(0.2)
        self.dense2    = nn.Linear(DENSE_UNITS, NUM_LABELS)

    def forward(self, x):
        x = self.embedding(x)
        x, _ = self.bilstm(x)
        x = x.max(dim=1).values
        x = self.relu(self.dense1(x))
        x = self.dropout(x)
        return torch.sigmoid(self.dense2(x))

device = "cuda" if torch.cuda.is_available() else "cpu"
model  = ToxicityModel().to(device)
print("Model ready on:", device)
print(model)

# ── optimizer & loss ───────────────────────────────────────────────────────────
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
loss_fn   = nn.BCELoss()

# ── training loop ──────────────────────────────────────────────────────────────
for epoch in range(EPOCHS):
    model.train()
    total_loss = 0
    for step, (xb, yb) in enumerate(train_loader):
        xb, yb = xb.to(device), yb.to(device)
        optimizer.zero_grad()
        preds = model(xb)
        loss  = loss_fn(preds, yb)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
        if step % 200 == 0:
            print(f"  Epoch {epoch+1} | step {step}/{len(train_loader)} | loss {loss.item():.4f}")

    model.eval()
    val_loss = 0
    with torch.no_grad():
        for xb, yb in val_loader:
            xb, yb = xb.to(device), yb.to(device)
            val_loss += loss_fn(model(xb), yb).item()

    print(f"\nEpoch {epoch+1} done | train loss: {total_loss/len(train_loader):.4f} | val loss: {val_loss/len(val_loader):.4f}\n")

print("Training complete!")

# ── CELL 7 : Test the model & save weights ────────────────────────────────────
from google.colab import files

LABEL_NAMES = ['Toxic', 'Severe Toxic', 'Obscene', 'Threat', 'Insult', 'Identity Hate']

# ── quick prediction test ──────────────────────────────────────────────────────
def predict(text):
    model.eval()
    with torch.no_grad():
        x = torch.tensor([tokenize(text)], dtype=torch.long).to(device)
        scores = model(x)[0].cpu().numpy()
    print(f"\nComment: \"{text}\"")
    print("-" * 50)
    for name, score in zip(LABEL_NAMES, scores):
        bar = '█' * int(score * 30)
        print(f"  {name:<15} {score:.2%}  {bar}")

predict("Thanks for the great explanation, really helpful!")
predict("You are such an idiot, go away!")

# ── save weights ───────────────────────────────────────────────────────────────
torch.save(model.state_dict(), "toxicity_pytorch_model.pt")
print("\n✅ Weights saved → toxicity_pytorch_model.pt")

# ── download both files to your computer ──────────────────────────────────────
files.download("toxicity_pytorch_model.pt")
files.download("vectorizer_vocab.pkl")
print("✅ Downloads started — check your browser downloads folder!")

